// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: apb/arachne.proto

package apb

import (
	cpb "github.com/portbuster1337/ArachneC2/protobuf/cpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Envelope wraps all messages sent between operator and implant
type Envelope struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID        int64  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Type      uint32 `protobuf:"varint,2,opt,name=Type,proto3" json:"Type,omitempty"`
	Data      []byte `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	Signature []byte `protobuf:"bytes,4,opt,name=Signature,proto3" json:"Signature,omitempty"`
	SenderKey []byte `protobuf:"bytes,5,opt,name=SenderKey,proto3" json:"SenderKey,omitempty"`
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apb_arachne_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_apb_arachne_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_apb_arachne_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Envelope) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Envelope) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Envelope) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Envelope) GetSenderKey() []byte {
	if x != nil {
		return x.SenderKey
	}
	return nil
}

// Register - First message implant sends after connecting
type Register struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name              string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Hostname          string `protobuf:"bytes,2,opt,name=Hostname,proto3" json:"Hostname,omitempty"`
	UUID              string `protobuf:"bytes,3,opt,name=UUID,proto3" json:"UUID,omitempty"`
	Username          string `protobuf:"bytes,4,opt,name=Username,proto3" json:"Username,omitempty"`
	UID               string `protobuf:"bytes,5,opt,name=UID,proto3" json:"UID,omitempty"`
	GID               string `protobuf:"bytes,6,opt,name=GID,proto3" json:"GID,omitempty"`
	OS                string `protobuf:"bytes,7,opt,name=OS,proto3" json:"OS,omitempty"`
	Arch              string `protobuf:"bytes,8,opt,name=Arch,proto3" json:"Arch,omitempty"`
	PID               int32  `protobuf:"varint,9,opt,name=PID,proto3" json:"PID,omitempty"`
	Filename          string `protobuf:"bytes,10,opt,name=Filename,proto3" json:"Filename,omitempty"`
	Version           string `protobuf:"bytes,11,opt,name=Version,proto3" json:"Version,omitempty"`
	PeerID            int64  `protobuf:"varint,12,opt,name=PeerID,proto3" json:"PeerID,omitempty"`
	ActiveC2          string `protobuf:"bytes,13,opt,name=ActiveC2,proto3" json:"ActiveC2,omitempty"`
	ReconnectInterval int64  `protobuf:"varint,14,opt,name=ReconnectInterval,proto3" json:"ReconnectInterval,omitempty"`
	Locale            string `protobuf:"bytes,15,opt,name=Locale,proto3" json:"Locale,omitempty"`
}

func (x *Register) Reset() {
	*x = Register{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apb_arachne_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Register) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Register) ProtoMessage() {}

func (x *Register) ProtoReflect() protoreflect.Message {
	mi := &file_apb_arachne_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Register.ProtoReflect.Descriptor instead.
func (*Register) Descriptor() ([]byte, []int) {
	return file_apb_arachne_proto_rawDescGZIP(), []int{1}
}

func (x *Register) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Register) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Register) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *Register) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Register) GetUID() string {
	if x != nil {
		return x.UID
	}
	return ""
}

func (x *Register) GetGID() string {
	if x != nil {
		return x.GID
	}
	return ""
}

func (x *Register) GetOS() string {
	if x != nil {
		return x.OS
	}
	return ""
}

func (x *Register) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *Register) GetPID() int32 {
	if x != nil {
		return x.PID
	}
	return 0
}

func (x *Register) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Register) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Register) GetPeerID() int64 {
	if x != nil {
		return x.PeerID
	}
	return 0
}

func (x *Register) GetActiveC2() string {
	if x != nil {
		return x.ActiveC2
	}
	return ""
}

func (x *Register) GetReconnectInterval() int64 {
	if x != nil {
		return x.ReconnectInterval
	}
	return 0
}

func (x *Register) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

// Z1 - Used for async beacon mode
type Z1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID          string    `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Interval    int64     `protobuf:"varint,2,opt,name=Interval,proto3" json:"Interval,omitempty"`
	Jitter      int64     `protobuf:"varint,3,opt,name=Jitter,proto3" json:"Jitter,omitempty"`
	Register    *Register `protobuf:"bytes,4,opt,name=Register,proto3" json:"Register,omitempty"`
	NextCheckin int64     `protobuf:"varint,5,opt,name=NextCheckin,proto3" json:"NextCheckin,omitempty"`
}

func (x *Z1) Reset() {
	*x = Z1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apb_arachne_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Z1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Z1) ProtoMessage() {}

func (x *Z1) ProtoReflect() protoreflect.Message {
	mi := &file_apb_arachne_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Z1.ProtoReflect.Descriptor instead.
func (*Z1) Descriptor() ([]byte, []int) {
	return file_apb_arachne_proto_rawDescGZIP(), []int{2}
}

func (x *Z1) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Z1) GetInterval() int64 {
	if x != nil {
		return x.Interval
	}
	return 0
}

func (x *Z1) GetJitter() int64 {
	if x != nil {
		return x.Jitter
	}
	return 0
}

func (x *Z1) GetRegister() *Register {
	if x != nil {
		return x.Register
	}
	return nil
}

func (x *Z1) GetNextCheckin() int64 {
	if x != nil {
		return x.NextCheckin
	}
	return 0
}

// Ping - Keepalive / round-trip test
type Ping struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nonce    int32         `protobuf:"varint,1,opt,name=Nonce,proto3" json:"Nonce,omitempty"`
	Response *cpb.Response `protobuf:"bytes,8,opt,name=Response,proto3" json:"Response,omitempty"`
	Request  *cpb.Request  `protobuf:"bytes,9,opt,name=Request,proto3" json:"Request,omitempty"`
}

func (x *Ping) Reset() {
	*x = Ping{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apb_arachne_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_apb_arachne_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_apb_arachne_proto_rawDescGZIP(), []int{3}
}

func (x *Ping) GetNonce() int32 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *Ping) GetResponse() *cpb.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *Ping) GetRequest() *cpb.Request {
	if x != nil {
		return x.Request
	}
	return nil
}

// Z4 - Request implant to die
type Z4 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request *cpb.Request `protobuf:"bytes,9,opt,name=Request,proto3" json:"Request,omitempty"`
}

func (x *Z4) Reset() {
	*x = Z4{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apb_arachne_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Z4) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Z4) ProtoMessage() {}

func (x *Z4) ProtoReflect() protoreflect.Message {
	mi := &file_apb_arachne_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Z4.ProtoReflect.Descriptor instead.
func (*Z4) Descriptor() ([]byte, []int) {
	return file_apb_arachne_proto_rawDescGZIP(), []int{4}
}

func (x *Z4) GetRequest() *cpb.Request {
	if x != nil {
		return x.Request
	}
	return nil
}

// Z12 - List processes
type Z12 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request *cpb.Request `protobuf:"bytes,9,opt,name=Request,proto3" json:"Request,omitempty"`
}

func (x *Z12) Reset() {
	*x = Z12{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apb_arachne_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Z12) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Z12) ProtoMessage() {}

func (x *Z12) ProtoReflect() protoreflect.Message {
	mi := &file_apb_arachne_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Z12.ProtoReflect.Descriptor instead.
func (*Z12) Descriptor() ([]byte, []int) {
	return file_apb_arachne_proto_rawDescGZIP(), []int{5}
}

func (x *Z12) GetRequest() *cpb.Request {
	if x != nil {
		return x.Request
	}
	return nil
}

type Z13 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Processes []*cpb.Process `protobuf:"bytes,1,rep,name=Processes,proto3" json:"Processes,omitempty"`
	Response  *cpb.Response  `protobuf:"bytes,9,opt,name=Response,proto3" json:"Response,omitempty"`
}

func (x *Z13) Reset() {
	*x = Z13{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apb_arachne_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Z13) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Z13) ProtoMessage() {}

func (x *Z13) ProtoReflect() protoreflect.Message {
	mi := &file_apb_arachne_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Z13.ProtoReflect.Descriptor instead.
func (*Z13) Descriptor() ([]byte, []int) {
	return file_apb_arachne_proto_rawDescGZIP(), []int{6}
}

func (x *Z13) GetProcesses() []*cpb.Process {
	if x != nil {
		return x.Processes
	}
	return nil
}

func (x *Z13) GetResponse() *cpb.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

// Z14 - Run a command
type Z14 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path    string       `protobuf:"bytes,1,opt,name=Path,proto3" json:"Path,omitempty"`
	Args    []string     `protobuf:"bytes,2,rep,name=Args,proto3" json:"Args,omitempty"`
	Output  bool         `protobuf:"varint,3,opt,name=Output,proto3" json:"Output,omitempty"`
	Request *cpb.Request `protobuf:"bytes,9,opt,name=Request,proto3" json:"Request,omitempty"`
}

func (x *Z14) Reset() {
	*x = Z14{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apb_arachne_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Z14) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Z14) ProtoMessage() {}

func (x *Z14) ProtoReflect() protoreflect.Message {
	mi := &file_apb_arachne_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Z14.ProtoReflect.Descriptor instead.
func (*Z14) Descriptor() ([]byte, []int) {
	return file_apb_arachne_proto_rawDescGZIP(), []int{7}
}

func (x *Z14) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Z14) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *Z14) GetOutput() bool {
	if x != nil {
		return x.Output
	}
	return false
}

func (x *Z14) GetRequest() *cpb.Request {
	if x != nil {
		return x.Request
	}
	return nil
}

type Z15 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status   uint32        `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Stdout   []byte        `protobuf:"bytes,2,opt,name=Stdout,proto3" json:"Stdout,omitempty"`
	Stderr   []byte        `protobuf:"bytes,3,opt,name=Stderr,proto3" json:"Stderr,omitempty"`
	Pid      uint32        `protobuf:"varint,4,opt,name=Pid,proto3" json:"Pid,omitempty"`
	Response *cpb.Response `protobuf:"bytes,9,opt,name=Response,proto3" json:"Response,omitempty"`
}

func (x *Z15) Reset() {
	*x = Z15{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apb_arachne_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Z15) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Z15) ProtoMessage() {}

func (x *Z15) ProtoReflect() protoreflect.Message {
	mi := &file_apb_arachne_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Z15.ProtoReflect.Descriptor instead.
func (*Z15) Descriptor() ([]byte, []int) {
	return file_apb_arachne_proto_rawDescGZIP(), []int{8}
}

func (x *Z15) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Z15) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

func (x *Z15) GetStderr() []byte {
	if x != nil {
		return x.Stderr
	}
	return nil
}

func (x *Z15) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Z15) GetResponse() *cpb.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

// Z16 - List directory
type Z16 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path    string       `protobuf:"bytes,1,opt,name=Path,proto3" json:"Path,omitempty"`
	Request *cpb.Request `protobuf:"bytes,9,opt,name=Request,proto3" json:"Request,omitempty"`
}

func (x *Z16) Reset() {
	*x = Z16{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apb_arachne_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Z16) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Z16) ProtoMessage() {}

func (x *Z16) ProtoReflect() protoreflect.Message {
	mi := &file_apb_arachne_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Z16.ProtoReflect.Descriptor instead.
func (*Z16) Descriptor() ([]byte, []int) {
	return file_apb_arachne_proto_rawDescGZIP(), []int{9}
}

func (x *Z16) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Z16) GetRequest() *cpb.Request {
	if x != nil {
		return x.Request
	}
	return nil
}

type Z18 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	IsDir   bool   `protobuf:"varint,2,opt,name=IsDir,proto3" json:"IsDir,omitempty"`
	Size    int64  `protobuf:"varint,3,opt,name=Size,proto3" json:"Size,omitempty"`
	ModTime int64  `protobuf:"varint,4,opt,name=ModTime,proto3" json:"ModTime,omitempty"`
	Mode    string `protobuf:"bytes,5,opt,name=Mode,proto3" json:"Mode,omitempty"`
	Link    string `protobuf:"bytes,6,opt,name=Link,proto3" json:"Link,omitempty"`
}

func (x *Z18) Reset() {
	*x = Z18{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apb_arachne_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Z18) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Z18) ProtoMessage() {}

func (x *Z18) ProtoReflect() protoreflect.Message {
	mi := &file_apb_arachne_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Z18.ProtoReflect.Descriptor instead.
func (*Z18) Descriptor() ([]byte, []int) {
	return file_apb_arachne_proto_rawDescGZIP(), []int{10}
}

func (x *Z18) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Z18) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *Z18) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Z18) GetModTime() int64 {
	if x != nil {
		return x.ModTime
	}
	return 0
}

func (x *Z18) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *Z18) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

type Z17 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path     string        `protobuf:"bytes,1,opt,name=Path,proto3" json:"Path,omitempty"`
	Exists   bool          `protobuf:"varint,2,opt,name=Exists,proto3" json:"Exists,omitempty"`
	Files    []*Z18        `protobuf:"bytes,3,rep,name=Files,proto3" json:"Files,omitempty"`
	Response *cpb.Response `protobuf:"bytes,9,opt,name=Response,proto3" json:"Response,omitempty"`
}

func (x *Z17) Reset() {
	*x = Z17{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apb_arachne_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Z17) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Z17) ProtoMessage() {}

func (x *Z17) ProtoReflect() protoreflect.Message {
	mi := &file_apb_arachne_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Z17.ProtoReflect.Descriptor instead.
func (*Z17) Descriptor() ([]byte, []int) {
	return file_apb_arachne_proto_rawDescGZIP(), []int{11}
}

func (x *Z17) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Z17) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *Z17) GetFiles() []*Z18 {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *Z17) GetResponse() *cpb.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

// Z19 - Change directory
type Z19 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path    string       `protobuf:"bytes,1,opt,name=Path,proto3" json:"Path,omitempty"`
	Request *cpb.Request `protobuf:"bytes,9,opt,name=Request,proto3" json:"Request,omitempty"`
}

func (x *Z19) Reset() {
	*x = Z19{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apb_arachne_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Z19) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Z19) ProtoMessage() {}

func (x *Z19) ProtoReflect() protoreflect.Message {
	mi := &file_apb_arachne_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Z19.ProtoReflect.Descriptor instead.
func (*Z19) Descriptor() ([]byte, []int) {
	return file_apb_arachne_proto_rawDescGZIP(), []int{12}
}

func (x *Z19) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Z19) GetRequest() *cpb.Request {
	if x != nil {
		return x.Request
	}
	return nil
}

type Z20 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request *cpb.Request `protobuf:"bytes,9,opt,name=Request,proto3" json:"Request,omitempty"`
}

func (x *Z20) Reset() {
	*x = Z20{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apb_arachne_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Z20) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Z20) ProtoMessage() {}

func (x *Z20) ProtoReflect() protoreflect.Message {
	mi := &file_apb_arachne_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Z20.ProtoReflect.Descriptor instead.
func (*Z20) Descriptor() ([]byte, []int) {
	return file_apb_arachne_proto_rawDescGZIP(), []int{13}
}

func (x *Z20) GetRequest() *cpb.Request {
	if x != nil {
		return x.Request
	}
	return nil
}

type Z21 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path     string        `protobuf:"bytes,1,opt,name=Path,proto3" json:"Path,omitempty"`
	Response *cpb.Response `protobuf:"bytes,9,opt,name=Response,proto3" json:"Response,omitempty"`
}

func (x *Z21) Reset() {
	*x = Z21{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apb_arachne_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Z21) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Z21) ProtoMessage() {}

func (x *Z21) ProtoReflect() protoreflect.Message {
	mi := &file_apb_arachne_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Z21.ProtoReflect.Descriptor instead.
func (*Z21) Descriptor() ([]byte, []int) {
	return file_apb_arachne_proto_rawDescGZIP(), []int{14}
}

func (x *Z21) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Z21) GetResponse() *cpb.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

// Z22 - Z23 file from implant
type Z22 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path    string       `protobuf:"bytes,1,opt,name=Path,proto3" json:"Path,omitempty"`
	Request *cpb.Request `protobuf:"bytes,9,opt,name=Request,proto3" json:"Request,omitempty"`
}

func (x *Z22) Reset() {
	*x = Z22{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apb_arachne_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Z22) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Z22) ProtoMessage() {}

func (x *Z22) ProtoReflect() protoreflect.Message {
	mi := &file_apb_arachne_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Z22.ProtoReflect.Descriptor instead.
func (*Z22) Descriptor() ([]byte, []int) {
	return file_apb_arachne_proto_rawDescGZIP(), []int{15}
}

func (x *Z22) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Z22) GetRequest() *cpb.Request {
	if x != nil {
		return x.Request
	}
	return nil
}

type Z23 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path     string        `protobuf:"bytes,1,opt,name=Path,proto3" json:"Path,omitempty"`
	Exists   bool          `protobuf:"varint,2,opt,name=Exists,proto3" json:"Exists,omitempty"`
	Data     []byte        `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	Response *cpb.Response `protobuf:"bytes,9,opt,name=Response,proto3" json:"Response,omitempty"`
}

func (x *Z23) Reset() {
	*x = Z23{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apb_arachne_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Z23) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Z23) ProtoMessage() {}

func (x *Z23) ProtoReflect() protoreflect.Message {
	mi := &file_apb_arachne_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Z23.ProtoReflect.Descriptor instead.
func (*Z23) Descriptor() ([]byte, []int) {
	return file_apb_arachne_proto_rawDescGZIP(), []int{16}
}

func (x *Z23) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Z23) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *Z23) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Z23) GetResponse() *cpb.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

// Z24 - Z25 file to implant
type Z24 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path      string       `protobuf:"bytes,1,opt,name=Path,proto3" json:"Path,omitempty"`
	Data      []byte       `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	Overwrite bool         `protobuf:"varint,3,opt,name=Overwrite,proto3" json:"Overwrite,omitempty"`
	Request   *cpb.Request `protobuf:"bytes,9,opt,name=Request,proto3" json:"Request,omitempty"`
}

func (x *Z24) Reset() {
	*x = Z24{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apb_arachne_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Z24) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Z24) ProtoMessage() {}

func (x *Z24) ProtoReflect() protoreflect.Message {
	mi := &file_apb_arachne_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Z24.ProtoReflect.Descriptor instead.
func (*Z24) Descriptor() ([]byte, []int) {
	return file_apb_arachne_proto_rawDescGZIP(), []int{17}
}

func (x *Z24) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Z24) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Z24) GetOverwrite() bool {
	if x != nil {
		return x.Overwrite
	}
	return false
}

func (x *Z24) GetRequest() *cpb.Request {
	if x != nil {
		return x.Request
	}
	return nil
}

type Z25 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path         string        `protobuf:"bytes,1,opt,name=Path,proto3" json:"Path,omitempty"`
	BytesWritten int32         `protobuf:"varint,2,opt,name=BytesWritten,proto3" json:"BytesWritten,omitempty"`
	Response     *cpb.Response `protobuf:"bytes,9,opt,name=Response,proto3" json:"Response,omitempty"`
}

func (x *Z25) Reset() {
	*x = Z25{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apb_arachne_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Z25) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Z25) ProtoMessage() {}

func (x *Z25) ProtoReflect() protoreflect.Message {
	mi := &file_apb_arachne_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Z25.ProtoReflect.Descriptor instead.
func (*Z25) Descriptor() ([]byte, []int) {
	return file_apb_arachne_proto_rawDescGZIP(), []int{18}
}

func (x *Z25) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Z25) GetBytesWritten() int32 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

func (x *Z25) GetResponse() *cpb.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

// Z2 - Capture screen
type Z2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request *cpb.Request `protobuf:"bytes,9,opt,name=Request,proto3" json:"Request,omitempty"`
}

func (x *Z2) Reset() {
	*x = Z2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apb_arachne_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Z2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Z2) ProtoMessage() {}

func (x *Z2) ProtoReflect() protoreflect.Message {
	mi := &file_apb_arachne_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Z2.ProtoReflect.Descriptor instead.
func (*Z2) Descriptor() ([]byte, []int) {
	return file_apb_arachne_proto_rawDescGZIP(), []int{19}
}

func (x *Z2) GetRequest() *cpb.Request {
	if x != nil {
		return x.Request
	}
	return nil
}

type Z3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data     []byte        `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	Response *cpb.Response `protobuf:"bytes,9,opt,name=Response,proto3" json:"Response,omitempty"`
}

func (x *Z3) Reset() {
	*x = Z3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apb_arachne_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Z3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Z3) ProtoMessage() {}

func (x *Z3) ProtoReflect() protoreflect.Message {
	mi := &file_apb_arachne_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Z3.ProtoReflect.Descriptor instead.
func (*Z3) Descriptor() ([]byte, []int) {
	return file_apb_arachne_proto_rawDescGZIP(), []int{20}
}

func (x *Z3) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Z3) GetResponse() *cpb.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

// Z5 - Open interactive shell
type Z5 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path      string       `protobuf:"bytes,1,opt,name=Path,proto3" json:"Path,omitempty"`
	EnablePTY bool         `protobuf:"varint,2,opt,name=EnablePTY,proto3" json:"EnablePTY,omitempty"`
	Pid       uint32       `protobuf:"varint,3,opt,name=Pid,proto3" json:"Pid,omitempty"`
	TunnelID  uint64       `protobuf:"varint,8,opt,name=TunnelID,proto3" json:"TunnelID,omitempty"`
	Request   *cpb.Request `protobuf:"bytes,9,opt,name=Request,proto3" json:"Request,omitempty"`
}

func (x *Z5) Reset() {
	*x = Z5{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apb_arachne_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Z5) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Z5) ProtoMessage() {}

func (x *Z5) ProtoReflect() protoreflect.Message {
	mi := &file_apb_arachne_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Z5.ProtoReflect.Descriptor instead.
func (*Z5) Descriptor() ([]byte, []int) {
	return file_apb_arachne_proto_rawDescGZIP(), []int{21}
}

func (x *Z5) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Z5) GetEnablePTY() bool {
	if x != nil {
		return x.EnablePTY
	}
	return false
}

func (x *Z5) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Z5) GetTunnelID() uint64 {
	if x != nil {
		return x.TunnelID
	}
	return 0
}

func (x *Z5) GetRequest() *cpb.Request {
	if x != nil {
		return x.Request
	}
	return nil
}

type Z6 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path      string        `protobuf:"bytes,1,opt,name=Path,proto3" json:"Path,omitempty"`
	EnablePTY bool          `protobuf:"varint,2,opt,name=EnablePTY,proto3" json:"EnablePTY,omitempty"`
	Pid       uint32        `protobuf:"varint,3,opt,name=Pid,proto3" json:"Pid,omitempty"`
	TunnelID  uint64        `protobuf:"varint,8,opt,name=TunnelID,proto3" json:"TunnelID,omitempty"`
	Response  *cpb.Response `protobuf:"bytes,9,opt,name=Response,proto3" json:"Response,omitempty"`
}

func (x *Z6) Reset() {
	*x = Z6{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apb_arachne_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Z6) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Z6) ProtoMessage() {}

func (x *Z6) ProtoReflect() protoreflect.Message {
	mi := &file_apb_arachne_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Z6.ProtoReflect.Descriptor instead.
func (*Z6) Descriptor() ([]byte, []int) {
	return file_apb_arachne_proto_rawDescGZIP(), []int{22}
}

func (x *Z6) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Z6) GetEnablePTY() bool {
	if x != nil {
		return x.EnablePTY
	}
	return false
}

func (x *Z6) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Z6) GetTunnelID() uint64 {
	if x != nil {
		return x.TunnelID
	}
	return 0
}

func (x *Z6) GetResponse() *cpb.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

// Z7 - Stream tunnel
type Z7 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TunnelID  uint64 `protobuf:"varint,8,opt,name=TunnelID,proto3" json:"TunnelID,omitempty"`
	SessionID string `protobuf:"bytes,9,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
}

func (x *Z7) Reset() {
	*x = Z7{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apb_arachne_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Z7) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Z7) ProtoMessage() {}

func (x *Z7) ProtoReflect() protoreflect.Message {
	mi := &file_apb_arachne_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Z7.ProtoReflect.Descriptor instead.
func (*Z7) Descriptor() ([]byte, []int) {
	return file_apb_arachne_proto_rawDescGZIP(), []int{23}
}

func (x *Z7) GetTunnelID() uint64 {
	if x != nil {
		return x.TunnelID
	}
	return 0
}

func (x *Z7) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

type Z8 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data      []byte `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	Closed    bool   `protobuf:"varint,2,opt,name=Closed,proto3" json:"Closed,omitempty"`
	Sequence  uint64 `protobuf:"varint,3,opt,name=Sequence,proto3" json:"Sequence,omitempty"`
	TunnelID  uint64 `protobuf:"varint,8,opt,name=TunnelID,proto3" json:"TunnelID,omitempty"`
	SessionID string `protobuf:"bytes,9,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
}

func (x *Z8) Reset() {
	*x = Z8{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apb_arachne_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Z8) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Z8) ProtoMessage() {}

func (x *Z8) ProtoReflect() protoreflect.Message {
	mi := &file_apb_arachne_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Z8.ProtoReflect.Descriptor instead.
func (*Z8) Descriptor() ([]byte, []int) {
	return file_apb_arachne_proto_rawDescGZIP(), []int{24}
}

func (x *Z8) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Z8) GetClosed() bool {
	if x != nil {
		return x.Closed
	}
	return false
}

func (x *Z8) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Z8) GetTunnelID() uint64 {
	if x != nil {
		return x.TunnelID
	}
	return 0
}

func (x *Z8) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

// Socks5 proxy
type Z9 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TunnelID  uint64 `protobuf:"varint,8,opt,name=TunnelID,proto3" json:"TunnelID,omitempty"`
	SessionID string `protobuf:"bytes,9,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
}

func (x *Z9) Reset() {
	*x = Z9{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apb_arachne_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Z9) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Z9) ProtoMessage() {}

func (x *Z9) ProtoReflect() protoreflect.Message {
	mi := &file_apb_arachne_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Z9.ProtoReflect.Descriptor instead.
func (*Z9) Descriptor() ([]byte, []int) {
	return file_apb_arachne_proto_rawDescGZIP(), []int{25}
}

func (x *Z9) GetTunnelID() uint64 {
	if x != nil {
		return x.TunnelID
	}
	return 0
}

func (x *Z9) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

type Z10 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data      []byte       `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	CloseConn bool         `protobuf:"varint,2,opt,name=CloseConn,proto3" json:"CloseConn,omitempty"`
	Sequence  uint64       `protobuf:"varint,5,opt,name=Sequence,proto3" json:"Sequence,omitempty"`
	TunnelID  uint64       `protobuf:"varint,8,opt,name=TunnelID,proto3" json:"TunnelID,omitempty"`
	Request   *cpb.Request `protobuf:"bytes,9,opt,name=Request,proto3" json:"Request,omitempty"`
}

func (x *Z10) Reset() {
	*x = Z10{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apb_arachne_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Z10) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Z10) ProtoMessage() {}

func (x *Z10) ProtoReflect() protoreflect.Message {
	mi := &file_apb_arachne_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Z10.ProtoReflect.Descriptor instead.
func (*Z10) Descriptor() ([]byte, []int) {
	return file_apb_arachne_proto_rawDescGZIP(), []int{26}
}

func (x *Z10) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Z10) GetCloseConn() bool {
	if x != nil {
		return x.CloseConn
	}
	return false
}

func (x *Z10) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Z10) GetTunnelID() uint64 {
	if x != nil {
		return x.TunnelID
	}
	return 0
}

func (x *Z10) GetRequest() *cpb.Request {
	if x != nil {
		return x.Request
	}
	return nil
}

// Z11 - IPFS-based exfiltration reference
type Z11 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CID      string        `protobuf:"bytes,1,opt,name=CID,proto3" json:"CID,omitempty"`
	Key      []byte        `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`
	FileName string        `protobuf:"bytes,3,opt,name=FileName,proto3" json:"FileName,omitempty"`
	Size     int64         `protobuf:"varint,4,opt,name=Size,proto3" json:"Size,omitempty"`
	Type     uint32        `protobuf:"varint,5,opt,name=Type,proto3" json:"Type,omitempty"`
	Response *cpb.Response `protobuf:"bytes,9,opt,name=Response,proto3" json:"Response,omitempty"`
}

func (x *Z11) Reset() {
	*x = Z11{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apb_arachne_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Z11) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Z11) ProtoMessage() {}

func (x *Z11) ProtoReflect() protoreflect.Message {
	mi := &file_apb_arachne_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Z11.ProtoReflect.Descriptor instead.
func (*Z11) Descriptor() ([]byte, []int) {
	return file_apb_arachne_proto_rawDescGZIP(), []int{27}
}

func (x *Z11) GetCID() string {
	if x != nil {
		return x.CID
	}
	return ""
}

func (x *Z11) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Z11) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *Z11) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Z11) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Z11) GetResponse() *cpb.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

var File_apb_arachne_proto protoreflect.FileDescriptor

var file_apb_arachne_proto_rawDesc = []byte{
	0x0a, 0x11, 0x61, 0x70, 0x62, 0x2f, 0x61, 0x72, 0x61, 0x63, 0x68, 0x6e, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x62, 0x1a, 0x10, 0x63, 0x70, 0x62, 0x2f, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7e, 0x0a, 0x08, 0x45, 0x6e,
	0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61,
	0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1c,
	0x0a, 0x09, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x09, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x09, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x22, 0xf4, 0x02, 0x0a, 0x08, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x48,
	0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x48,
	0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x55, 0x55, 0x49, 0x44, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x55, 0x55, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x55,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x44, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x47, 0x49, 0x44,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x47, 0x49, 0x44, 0x12, 0x0e, 0x0a, 0x02, 0x4f,
	0x53, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x4f, 0x53, 0x12, 0x12, 0x0a, 0x04, 0x41,
	0x72, 0x63, 0x68, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x41, 0x72, 0x63, 0x68, 0x12,
	0x10, 0x0a, 0x03, 0x50, 0x49, 0x44, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x50, 0x49,
	0x44, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x65, 0x65, 0x72, 0x49,
	0x44, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x50, 0x65, 0x65, 0x72, 0x49, 0x44, 0x12,
	0x1a, 0x0a, 0x08, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x43, 0x32, 0x18, 0x0d, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x43, 0x32, 0x12, 0x2c, 0x0a, 0x11, 0x52,
	0x65, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c,
	0x18, 0x0e, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x52, 0x65, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x4c, 0x6f, 0x63,
	0x61, 0x6c, 0x65, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4c, 0x6f, 0x63, 0x61, 0x6c,
	0x65, 0x22, 0x95, 0x01, 0x0a, 0x02, 0x5a, 0x31, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x76, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x76, 0x61, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x4a, 0x69, 0x74, 0x74, 0x65, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x4a, 0x69, 0x74, 0x74, 0x65, 0x72, 0x12, 0x29, 0x0a, 0x08,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x61, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x08, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x4e, 0x65, 0x78, 0x74, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x4e, 0x65,
	0x78, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x22, 0x6f, 0x0a, 0x04, 0x50, 0x69, 0x6e,
	0x67, 0x12, 0x14, 0x0a, 0x05, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x29, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x63, 0x70, 0x62, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x26, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x52, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x2c, 0x0a, 0x02, 0x5a, 0x34,
	0x12, 0x26, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52,
	0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x2d, 0x0a, 0x03, 0x5a, 0x31, 0x32, 0x12,
	0x26, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x63, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x07,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x5c, 0x0a, 0x03, 0x5a, 0x31, 0x33, 0x12, 0x2a,
	0x0a, 0x09, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x70, 0x62, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x52,
	0x09, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x73, 0x12, 0x29, 0x0a, 0x08, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x63,
	0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x6d, 0x0a, 0x03, 0x5a, 0x31, 0x34, 0x12, 0x12, 0x0a, 0x04,
	0x50, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x50, 0x61, 0x74, 0x68,
	0x12, 0x12, 0x0a, 0x04, 0x41, 0x72, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04,
	0x41, 0x72, 0x67, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x26, 0x0a, 0x07,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x63, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x07, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x8a, 0x01, 0x0a, 0x03, 0x5a, 0x31, 0x35, 0x12, 0x16, 0x0a, 0x06,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x64, 0x6f, 0x75, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x53, 0x74, 0x64, 0x6f, 0x75, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x53, 0x74, 0x64, 0x65, 0x72, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x53, 0x74,
	0x64, 0x65, 0x72, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x50, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x03, 0x50, 0x69, 0x64, 0x12, 0x29, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x63, 0x70, 0x62, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x41, 0x0a, 0x03, 0x5a, 0x31, 0x36, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61, 0x74, 0x68,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x50, 0x61, 0x74, 0x68, 0x12, 0x26, 0x0a, 0x07,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x63, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x07, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x85, 0x01, 0x0a, 0x03, 0x5a, 0x31, 0x38, 0x12, 0x12, 0x0a, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x49, 0x73, 0x44, 0x69, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x05, 0x49, 0x73, 0x44, 0x69, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x6f,
	0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x4d, 0x6f, 0x64,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4d, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4c, 0x69, 0x6e, 0x6b,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4c, 0x69, 0x6e, 0x6b, 0x22, 0x7c, 0x0a, 0x03,
	0x5a, 0x31, 0x37, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x50, 0x61, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x45, 0x78, 0x69, 0x73, 0x74,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x12,
	0x1e, 0x0a, 0x05, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08,
	0x2e, 0x61, 0x70, 0x62, 0x2e, 0x5a, 0x31, 0x38, 0x52, 0x05, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x12,
	0x29, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x63, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x52, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x41, 0x0a, 0x03, 0x5a, 0x31,
	0x39, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x50, 0x61, 0x74, 0x68, 0x12, 0x26, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x52, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x2d, 0x0a,
	0x03, 0x5a, 0x32, 0x30, 0x12, 0x26, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x52, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x44, 0x0a, 0x03,
	0x5a, 0x32, 0x31, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x50, 0x61, 0x74, 0x68, 0x12, 0x29, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x63, 0x70, 0x62, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x41, 0x0a, 0x03, 0x5a, 0x32, 0x32, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61, 0x74,
	0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x50, 0x61, 0x74, 0x68, 0x12, 0x26, 0x0a,
	0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x63, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x07, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x70, 0x0a, 0x03, 0x5a, 0x32, 0x33, 0x12, 0x12, 0x0a, 0x04,
	0x50, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x50, 0x61, 0x74, 0x68,
	0x12, 0x16, 0x0a, 0x06, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x06, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x29, 0x0a, 0x08,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x63, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x73, 0x0a, 0x03, 0x5a, 0x32, 0x34, 0x12, 0x12,
	0x0a, 0x04, 0x50, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x50, 0x61,
	0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09, 0x4f, 0x76, 0x65, 0x72, 0x77, 0x72,
	0x69, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x4f, 0x76, 0x65, 0x72, 0x77,
	0x72, 0x69, 0x74, 0x65, 0x12, 0x26, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x52, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x68, 0x0a, 0x03,
	0x5a, 0x32, 0x35, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x50, 0x61, 0x74, 0x68, 0x12, 0x22, 0x0a, 0x0c, 0x42, 0x79, 0x74, 0x65, 0x73,
	0x57, 0x72, 0x69, 0x74, 0x74, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x42,
	0x79, 0x74, 0x65, 0x73, 0x57, 0x72, 0x69, 0x74, 0x74, 0x65, 0x6e, 0x12, 0x29, 0x0a, 0x08, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x63, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2c, 0x0a, 0x02, 0x5a, 0x32, 0x12, 0x26, 0x0a, 0x07,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x63, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x07, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x43, 0x0a, 0x02, 0x5a, 0x33, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x29,
	0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x63, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52,
	0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x8c, 0x01, 0x0a, 0x02, 0x5a, 0x35,
	0x12, 0x12, 0x0a, 0x04, 0x50, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x50, 0x61, 0x74, 0x68, 0x12, 0x1c, 0x0a, 0x09, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x50, 0x54,
	0x59, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x50,
	0x54, 0x59, 0x12, 0x10, 0x0a, 0x03, 0x50, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x03, 0x50, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x44,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x44,
	0x12, 0x26, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52,
	0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x8f, 0x01, 0x0a, 0x02, 0x5a, 0x36, 0x12,
	0x12, 0x0a, 0x04, 0x50, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x50,
	0x61, 0x74, 0x68, 0x12, 0x1c, 0x0a, 0x09, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x50, 0x54, 0x59,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x50, 0x54,
	0x59, 0x12, 0x10, 0x0a, 0x03, 0x50, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03,
	0x50, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x44, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x44, 0x12,
	0x29, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x63, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x52, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x3e, 0x0a, 0x02, 0x5a, 0x37,
	0x12, 0x1a, 0x0a, 0x08, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x44, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x08, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x22, 0x86, 0x01, 0x0a, 0x02, 0x5a,
	0x38, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x08, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x54, 0x75, 0x6e,
	0x6e, 0x65, 0x6c, 0x49, 0x44, 0x18, 0x08, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x54, 0x75, 0x6e,
	0x6e, 0x65, 0x6c, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x49, 0x44, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x49, 0x44, 0x22, 0x3e, 0x0a, 0x02, 0x5a, 0x39, 0x12, 0x1a, 0x0a, 0x08, 0x54, 0x75, 0x6e,
	0x6e, 0x65, 0x6c, 0x49, 0x44, 0x18, 0x08, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x54, 0x75, 0x6e,
	0x6e, 0x65, 0x6c, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x49, 0x44, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x49, 0x44, 0x22, 0x97, 0x01, 0x0a, 0x03, 0x5a, 0x31, 0x30, 0x12, 0x12, 0x0a, 0x04, 0x44,
	0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x1c, 0x0a, 0x09, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x09, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x12, 0x1a, 0x0a,
	0x08, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x08, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x54, 0x75, 0x6e,
	0x6e, 0x65, 0x6c, 0x49, 0x44, 0x18, 0x08, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x54, 0x75, 0x6e,
	0x6e, 0x65, 0x6c, 0x49, 0x44, 0x12, 0x26, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x52, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x98, 0x01,
	0x0a, 0x03, 0x5a, 0x31, 0x31, 0x12, 0x10, 0x0a, 0x03, 0x43, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x43, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x69, 0x6c,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x46, 0x69, 0x6c,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x29, 0x0a,
	0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x63, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x6f, 0x72, 0x74, 0x62, 0x75, 0x73, 0x74, 0x65,
	0x72, 0x31, 0x33, 0x33, 0x37, 0x2f, 0x41, 0x72, 0x61, 0x63, 0x68, 0x6e, 0x65, 0x43, 0x32, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_apb_arachne_proto_rawDescOnce sync.Once
	file_apb_arachne_proto_rawDescData = file_apb_arachne_proto_rawDesc
)

func file_apb_arachne_proto_rawDescGZIP() []byte {
	file_apb_arachne_proto_rawDescOnce.Do(func() {
		file_apb_arachne_proto_rawDescData = protoimpl.X.CompressGZIP(file_apb_arachne_proto_rawDescData)
	})
	return file_apb_arachne_proto_rawDescData
}

var file_apb_arachne_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_apb_arachne_proto_goTypes = []interface{}{
	(*Envelope)(nil),     // 0: apb.Envelope
	(*Register)(nil),     // 1: apb.Register
	(*Z1)(nil),           // 2: apb.Z1
	(*Ping)(nil),         // 3: apb.Ping
	(*Z4)(nil),           // 4: apb.Z4
	(*Z12)(nil),          // 5: apb.Z12
	(*Z13)(nil),          // 6: apb.Z13
	(*Z14)(nil),          // 7: apb.Z14
	(*Z15)(nil),          // 8: apb.Z15
	(*Z16)(nil),          // 9: apb.Z16
	(*Z18)(nil),          // 10: apb.Z18
	(*Z17)(nil),          // 11: apb.Z17
	(*Z19)(nil),          // 12: apb.Z19
	(*Z20)(nil),          // 13: apb.Z20
	(*Z21)(nil),          // 14: apb.Z21
	(*Z22)(nil),          // 15: apb.Z22
	(*Z23)(nil),          // 16: apb.Z23
	(*Z24)(nil),          // 17: apb.Z24
	(*Z25)(nil),          // 18: apb.Z25
	(*Z2)(nil),           // 19: apb.Z2
	(*Z3)(nil),           // 20: apb.Z3
	(*Z5)(nil),           // 21: apb.Z5
	(*Z6)(nil),           // 22: apb.Z6
	(*Z7)(nil),           // 23: apb.Z7
	(*Z8)(nil),           // 24: apb.Z8
	(*Z9)(nil),           // 25: apb.Z9
	(*Z10)(nil),          // 26: apb.Z10
	(*Z11)(nil),          // 27: apb.Z11
	(*cpb.Response)(nil), // 28: cpb.Response
	(*cpb.Request)(nil),  // 29: cpb.Request
	(*cpb.Process)(nil),  // 30: cpb.Process
}
var file_apb_arachne_proto_depIdxs = []int32{
	1,  // 0: apb.Z1.Register:type_name -> apb.Register
	28, // 1: apb.Ping.Response:type_name -> cpb.Response
	29, // 2: apb.Ping.Request:type_name -> cpb.Request
	29, // 3: apb.Z4.Request:type_name -> cpb.Request
	29, // 4: apb.Z12.Request:type_name -> cpb.Request
	30, // 5: apb.Z13.Processes:type_name -> cpb.Process
	28, // 6: apb.Z13.Response:type_name -> cpb.Response
	29, // 7: apb.Z14.Request:type_name -> cpb.Request
	28, // 8: apb.Z15.Response:type_name -> cpb.Response
	29, // 9: apb.Z16.Request:type_name -> cpb.Request
	10, // 10: apb.Z17.Files:type_name -> apb.Z18
	28, // 11: apb.Z17.Response:type_name -> cpb.Response
	29, // 12: apb.Z19.Request:type_name -> cpb.Request
	29, // 13: apb.Z20.Request:type_name -> cpb.Request
	28, // 14: apb.Z21.Response:type_name -> cpb.Response
	29, // 15: apb.Z22.Request:type_name -> cpb.Request
	28, // 16: apb.Z23.Response:type_name -> cpb.Response
	29, // 17: apb.Z24.Request:type_name -> cpb.Request
	28, // 18: apb.Z25.Response:type_name -> cpb.Response
	29, // 19: apb.Z2.Request:type_name -> cpb.Request
	28, // 20: apb.Z3.Response:type_name -> cpb.Response
	29, // 21: apb.Z5.Request:type_name -> cpb.Request
	28, // 22: apb.Z6.Response:type_name -> cpb.Response
	29, // 23: apb.Z10.Request:type_name -> cpb.Request
	28, // 24: apb.Z11.Response:type_name -> cpb.Response
	25, // [25:25] is the sub-list for method output_type
	25, // [25:25] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_apb_arachne_proto_init() }
func file_apb_arachne_proto_init() {
	if File_apb_arachne_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_apb_arachne_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Envelope); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apb_arachne_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Register); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apb_arachne_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Z1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apb_arachne_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ping); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apb_arachne_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Z4); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apb_arachne_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Z12); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apb_arachne_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Z13); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apb_arachne_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Z14); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apb_arachne_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Z15); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apb_arachne_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Z16); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apb_arachne_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Z18); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apb_arachne_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Z17); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apb_arachne_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Z19); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apb_arachne_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Z20); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apb_arachne_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Z21); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apb_arachne_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Z22); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apb_arachne_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Z23); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apb_arachne_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Z24); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apb_arachne_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Z25); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apb_arachne_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Z2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apb_arachne_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Z3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apb_arachne_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Z5); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apb_arachne_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Z6); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apb_arachne_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Z7); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apb_arachne_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Z8); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apb_arachne_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Z9); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apb_arachne_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Z10); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apb_arachne_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Z11); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apb_arachne_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apb_arachne_proto_goTypes,
		DependencyIndexes: file_apb_arachne_proto_depIdxs,
		MessageInfos:      file_apb_arachne_proto_msgTypes,
	}.Build()
	File_apb_arachne_proto = out.File
	file_apb_arachne_proto_rawDesc = nil
	file_apb_arachne_proto_goTypes = nil
	file_apb_arachne_proto_depIdxs = nil
}
