package main

import (
	"fmt"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

func main() {
	pubPath := defaultPubKeyPath()
	outputPath := "bin/implant"

	switch len(os.Args) {
	case 1:
	case 2:
		pubPath = os.Args[1]
	case 3:
		pubPath = os.Args[1]
		outputPath = os.Args[2]
	default:
		log.Fatalf("usage: build-implant [<operator.pub>] [<output-path>]")
	}
	data, err := os.ReadFile(pubPath)
	if err != nil {
		log.Fatalf("read %s: %v", pubPath, err)
	}

	var parts []string
	for _, b := range data {
		parts = append(parts, fmt.Sprintf("%d", b))
	}
	literal := "[]byte{" + strings.Join(parts, ",") + "}"

	root, err := findProjectRoot()
	if err != nil {
		log.Fatalf("find project root: %v", err)
	}

	genPath := root + "/implant/core/embedded_pubkey.go"
	genContent := fmt.Sprintf(`// Code generated by build-implant tool. DO NOT EDIT.
package core

var embeddedOperatorPubKey = %s
`, literal)

	if err := os.WriteFile(genPath, []byte(genContent), 0644); err != nil {
		log.Fatalf("write %s: %v", genPath, err)
	}
	log.Printf("wrote %s (%d bytes embedded)", genPath, len(data))

	outPath := filepath.Join(root, outputPath)

	goBinary := "go"
	if goroot := os.Getenv("GOROOT"); goroot != "" {
		candidate := filepath.Join(goroot, "bin", "go")
		if fileExists(candidate) {
			goBinary = candidate
		}
	}
	cmd := exec.Command(goBinary, "build", "-o", outPath, "-ldflags=-s -w", "./implant/")
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	cmd.Dir = root
	if err := cmd.Run(); err != nil {
		log.Fatalf("build: %v", err)
	}
	log.Printf("built %s", outPath)

	if upxPath, err := exec.LookPath("upx"); err == nil {
		upx := exec.Command(upxPath, "--best", "--lzma", outPath)
		upx.Dir = root
		upx.Stdout = os.Stdout
		upx.Stderr = os.Stderr
		if err := upx.Run(); err != nil {
			log.Printf("upx compression skipped: %v", err)
		}
	} else {
		log.Printf("upx not found, skipping compression")
	}
}

func defaultPubKeyPath() string {
	home, err := os.UserHomeDir()
	if err != nil {
		return "operator.pub"
	}
	return filepath.Join(home, ".arachne", "operator.pub")
}

func findProjectRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if fileExists(filepath.Join(dir, "go.mod")) {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("no go.mod found (run from project root)")
		}
		dir = parent
	}
}

func fileExists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}
